# -*- coding: utf-8 -*-
"""Restaurant Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAWbhLaO9iJh7Ovpz-bs4DB1exlRSMCs

#### Restaurant Recommendation System | Arizona, United States of America

#### Library and Data Import
"""

import pandas as pd
import numpy as np
import spacy
from collections import Counter
import matplotlib.pyplot as plt

# Loading the dataset
rest_data = pd.read_csv('/content/drive/MyDrive/Unstructured Data Analytics/Lab Assignment 1/restaurant_reviews_az.csv')

# Displaying the first few rows of the dataset
rest_data.head()

# Displaying the summary of the data
rest_data.info()

"""#### Selecting 1-Star and 5-Star Reviews"""

# Filtering for 1 star and 5 star reviews
one_star_reviews = rest_data[rest_data['stars'] == 1]
five_star_reviews = rest_data[rest_data['stars'] == 5]

# Showing the number of reviews for each
print(f"Number of 1 star reviews: {len(one_star_reviews)}")
print(f"Number of 5 star reviews: {len(five_star_reviews)}")

"""#### Text Processing"""

# Loading Spacy's English language model
nlp = spacy.load('en_core_web_sm')

def process_reviews(reviews):
    # Tokenization and processing
    processed_reviews = []
    for doc in nlp.pipe(reviews['text']):
        tokens = [token.lemma_.lower() for token in doc if not token.is_stop and not token.is_punct and not token.is_space]
        processed_reviews.append(tokens)
    return processed_reviews

# Processing the reviews
processed_one_star = process_reviews(one_star_reviews)
processed_five_star = process_reviews(five_star_reviews)

"""#### Top 20 Frequently Used Nouns"""

def get_top_pos(reviews, pos, n=20):
    # Counting words based on their part-of-speech tag
    words = [token.text.lower() for review in reviews for token in nlp(" ".join(review)) if token.pos_ == pos]
    word_freq = Counter(words)
    return word_freq.most_common(n)

# Getting the top nouns
top_nouns_one_star = get_top_pos(processed_one_star, 'NOUN')
top_nouns_five_star = get_top_pos(processed_five_star, 'NOUN')

# Display the results
print("Top 20 nouns in 1-star reviews:", top_nouns_one_star)
print("Top 20 nouns in 5-star reviews:", top_nouns_five_star)

"""#### Top 20 Frequently Used Adjectives"""

# Getting the top adjectives
top_adjectives_one_star = get_top_pos(processed_one_star, 'ADJ')
top_adjectives_five_star = get_top_pos(processed_five_star, 'ADJ')

# Display the results
print("Top 20 adjectives in 1-star reviews:", top_adjectives_one_star)
print("Top 20 adjectives in 5-star reviews:", top_adjectives_five_star)

"""#### Top 20 Frequently Used Verbs"""

# Getting the top verbs
top_verbs_one_star = get_top_pos(processed_one_star, 'VERB')
top_verbs_five_star = get_top_pos(processed_five_star, 'VERB')

# Display the results
print("Top 20 verbs in 1-star reviews:", top_verbs_one_star)
print("Top 20 verbs in 5-star reviews:", top_verbs_five_star)

"""#### Top 20 Frequently Used Named Entities"""

def get_top_entities(reviews, n=20):
    entities = [ent.text.lower() for review in reviews for ent in nlp(" ".join(review)).ents]
    entity_freq = Counter(entities)
    return entity_freq.most_common(n)

# Getting the top entities
top_entities_one_star = get_top_entities(processed_one_star)
top_entities_five_star = get_top_entities(processed_five_star)

# Display the results
print("Top 20 named entities in 1-star reviews:", top_entities_one_star)
print("Top 20 named entities in 5-star reviews:", top_entities_five_star)

"""#  **Observations, Comparisons and Conclusion**

## **Observations**
#### **Noun Usage**
**1-Star Reviews:** Common nouns include 'order', 'time', 'service', 'minute', 'customer', and 'manager'. This suggests a focus on the logistical and service aspects of the restaurant experience, possibly highlighting issues related to order accuracy, wait times, and customer service.

**5-Star Reviews:** Nouns like 'food', 'place', 'service', 'love', and 'staff' are frequent. This indicates a more positive sentiment, emphasizing the quality of food and the overall experience, including the place and the staff's performance.

-------------------------------------------------------------------------------

#### **Adjective Usage:**
**1-Star Reviews:** Adjectives such as 'bad', 'terrible', 'horrible', 'cold', and 'rude' are prevalent. These adjectives are strongly negative, indicating dissatisfaction with the quality of food and service.

**5-Star Reviews:** Here, we see 'good', 'great', 'amazing', 'friendly', and 'delicious'. These are positive descriptors, focusing on the excellence of food, service, and the overall pleasant experience.

-------------------------------------------------------------------------------

#### **Verb Usage:**

**1-Star Reviews:** Verbs like 'come', 'go', 'say', 'ask', and 'wait' are common. This might reflect experiences where customers had to engage in communication with the staff (possibly due to issues) or instances of prolonged waiting.

**5-Star Reviews:** The use of 'come', 'try', 'get', 'go', and 'eat' in a more positive context, perhaps reflecting satisfaction with the dining experience and a willingness to recommend or revisit the restaurant.

-------------------------------------------------------------------------------

#### **Named Entity Usage:**
**1-Star Reviews:** Numbers (like '2', '3', '1') and time-related terms ('today', 'tonight', 'minute', 'hour') are frequent. This could indicate complaints about waiting times and portions.

**5-Star Reviews:** Cuisine types ('Mexican', 'Italian', 'Thai', 'Chinese') and positive time references ('today', 'tonight') are prominent. This suggests that positive reviews often commend specific types of cuisine and the timeliness of service.

-------------------------------------------------------------------------------

## **Comparisons**
**Service Quality:** The frequent mention of service-related terms in 1-star reviews (like 'wait', 'customer', 'manager') compared to their relative rarity in 5-star reviews suggests that poor service is a significant factor in negative dining experiences.

**Food Quality:** The prominence of 'food' in both 1-star and 5-star reviews indicates its central role in the dining experience, but the context differs greatly (e.g., 'bad', 'cold' in 1-star vs. 'good', 'delicious' in 5-star).

**Specificity in Praise vs. Complaints:** 5-star reviews often mention specific types of cuisine and positive aspects, while 1-star reviews focus more on the negative aspects of service and logistics.

-------------------------------------------------------------------------------

## **Conclusion**
The key to a good restaurant experience, as reflected in the 5-star reviews, can be attributed to the quality of both food and service, coupled with a positive dining experience. Timeliness, courteous service, and high-quality cuisine are pivotal. In contrast, negative experiences are often marked by poor service, logistical issues, and dissatisfaction with food quality.

#### **Acknowledgement**: ChatGPT 4.0 for help with Syntax and resolution of issues in the code
"""